import 'dotenv/config';
import crypto from 'node:crypto';
import { isScryptHash } from './secure-room.js';

const ROOM_ID_PATTERN = /^[a-zA-Z0-9][a-zA-Z0-9_-]{2,63}$/;

const isProduction = process.env.NODE_ENV === 'production';
const roomId = process.env.CHAT_ROOM_ID || 'private-room';
const accessProofHash = process.env.CHAT_ACCESS_PROOF_HASH?.trim();
const password = process.env.CHAT_PASSWORD;
const tokenSecret = process.env.CHAT_TOKEN_SECRET || (!isProduction ? crypto.randomBytes(32).toString('base64url') : '');
const tokenTtlMinutes = numberFromEnv('TOKEN_TTL_MINUTES', 43200);
const messageMaxLength = numberFromEnv('MESSAGE_MAX_LENGTH', 1200);
const encryptedMessageMaxLength = numberFromEnv('ENCRYPTED_MESSAGE_MAX_LENGTH', 6000);
const clientOrigins = originListFromEnv('CLIENT_ORIGIN', [
  'http://localhost:5173',
  'https://chat-frontend-blond-two.vercel.app',
  'https://chat-frontend-cwm8.onrender.com'
]);

const errors = [];
const warnings = [];

if (!ROOM_ID_PATTERN.test(roomId)) {
  errors.push('CHAT_ROOM_ID must be 3-64 characters and use letters, numbers, underscores, or hyphens.');
}

if (!accessProofHash && !password) {
  errors.push('Set CHAT_ACCESS_PROOF_HASH or CHAT_PASSWORD.');
}

if (accessProofHash && !isScryptHash(accessProofHash)) {
  errors.push('CHAT_ACCESS_PROOF_HASH must be generated by npm run make-secret.');
}

if (password && password.length < 16) {
  errors.push('CHAT_PASSWORD must be at least 16 characters.');
}

if (!process.env.CHAT_TOKEN_SECRET && !isProduction) {
  warnings.push('CHAT_TOKEN_SECRET is not set. Using an ephemeral development secret for this process.');
}

if (!tokenSecret || tokenSecret.length < 32) {
  errors.push('CHAT_TOKEN_SECRET must be at least 32 characters.');
}

if (tokenTtlMinutes < 5 || tokenTtlMinutes > 525600) {
  errors.push('TOKEN_TTL_MINUTES must be between 5 and 525600.');
}

if (messageMaxLength < 1 || messageMaxLength > 4000) {
  errors.push('MESSAGE_MAX_LENGTH must be between 1 and 4000.');
}

if (encryptedMessageMaxLength < 500 || encryptedMessageMaxLength > 20000) {
  errors.push('ENCRYPTED_MESSAGE_MAX_LENGTH must be between 500 and 20000.');
}

if (clientOrigins.length === 0) {
  errors.push('CLIENT_ORIGIN must include at least one valid frontend origin.');
}

if (errors.length > 0) {
  throw new Error(`Configuration error:\n- ${errors.join('\n- ')}`);
}

for (const warning of warnings) {
  console.warn(`[config] ${warning}`);
}

export const config = Object.freeze({
  isProduction,
  port: numberFromEnv('PORT', 4000),
  clientOrigins,
  roomId,
  accessProofHash,
  password,
  tokenSecret,
  tokenTtlMs: tokenTtlMinutes * 60 * 1000,
  messageMaxLength,
  encryptedMessageMaxLength,
  requireHttps: isProduction && process.env.REQUIRE_HTTPS !== 'false',
  roomCapacity: 2
});

function listFromEnv(name, fallback) {
  const value = process.env[name];
  if (!value) {
    return fallback;
  }

  return value
    .split(',')
    .map((item) => item.trim())
    .filter(Boolean);
}

function originListFromEnv(name, fallback) {
  return listFromEnv(name, fallback)
    .map(normalizeOrigin)
    .filter(Boolean);
}

function normalizeOrigin(value) {
  try {
    return new URL(value).origin;
  } catch {
    warnings.push(`Ignoring invalid ${value} entry in CLIENT_ORIGIN.`);
    return null;
  }
}

function numberFromEnv(name, fallback) {
  const raw = process.env[name];
  if (!raw) {
    return fallback;
  }

  const value = Number(raw);
  return Number.isFinite(value) ? value : fallback;
}
